name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build: [Debug, Release]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Configure
      run: cmake -B ${{ github.workspace }}/build/
    - name: Build
      run: cmake --build ${{ github.workspace }}/build/ --config ${{ matrix.build }}
    - name: Test
      working-directory: ${{ github.workspace }}/build/
      run: ctest -C ${{ matrix.build }}
  
  build-linux:
    runs-on: ubuntu-latest
    env:
      CC: gcc-10
      CXX: g++-10
    strategy:
      fail-fast: false
      matrix:
        build: [Debug, Release]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup OpenGL
      run: sudo apt-get install libgl-dev
    - name: Install GLFW dependencies  
      run: sudo apt-get update && sudo apt-get install xorg-dev
    - name: Configure
      run: cmake -B ${{ github.workspace }}/build/ -DCMAKE_BUILD_TYPE=${{ matrix.build }}
    - name: Build
      run: cmake --build ${{ github.workspace }}/build/ --config ${{ matrix.build }}
    - name: Test
      working-directory: ${{ github.workspace }}/build/
      run: ctest -C ${{ matrix.build }}
