name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - name: Setup OpenGL
      run: sudo apt-get install libgl-dev
    - name: Install GLFW dependencies  
      run: sudo apt-get update && sudo apt-get install xorg-dev
    - name: Configure
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}
    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build_type }}
  
  build-windows:
    runs-on: windows-latest
    strategy:
     matrix:
      build_type: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - name: Configure
      run: cmake -B ${{ github.workspace }}/build
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}
    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build_type }}
  
