name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
     matrix:
      os: [ubuntu-latest, windows-latest]
      build: [Debug, Release]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup OpenGL and install GLFW dependencies
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install libgl-dev xorg-dev
    - name: Configure
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build }}
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build }}
    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.build }}
  
